### ISSUE TITLE
configure error on RHEL7.3 - "No package 'dbus-1' found"

### ISSUE THREAD

**Issue by yunyings** [01org/tpm2-abrmd#101]
I'm trying to compile latest master code on RHEL 7.3, getting error below when doing configure:
```
checking for DBUS... no
configure: error: Package requirements (dbus-1) were not met:

No package 'dbus-1' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DBUS_CFLAGS
and DBUS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

It seems dbus-1 is the devel package of dbus on Ubuntu, but I couldn't find same package on RHEL 7.3/EPEL7.

**Comment by mgerstner** [comment]
I think this might be named 'dbus-devel' on RHEL.

**Comment by flihp** [comment]
Centos calls this package [dbus-devel](http://centos-packages.com/6/package/dbus-devel/) as @mgerstner suggests. Unfortunately the online RHEL package search engine requires some sort of "RedHat account" that I don't have. If you've got a RHEL login you can go to https://access.redhat.com/downloads/content/package-browser to search for the right package.

**Comment by flihp** [comment]
Hope this helps. If not feel free to re-open the issue.

**Comment by yunyings** [comment]
Thanks Philip and Matthias for the help.

Found dbus-devel package under RHEL7.3 ISO image packages. After installing dbus-devel, dbus-1.pc is available and configure succeeds.
