### ISSUE TITLE
tpm2-abrmd.service location does not meet Fedora packaging guideline

### ISSUE THREAD

**Issue by yunyings** [01org/tpm2-abrmd#115]
Currently tpm2-abrmd.service is placed at:
/usr/lib64/systemd/system/tpm2-abrmd.service

When packing tpm2-abrmd for Fedora, finding that the place of tpm2-abrmd.service is against the rule of Fedora: https://fedoraproject.org/wiki/Packaging:Systemd#Filesystem_locations
"Packages with systemd unit files must put them into %{_unitdir}. %{_unitdir} evaluates to /lib/systemd/system on all Fedora systems (F-15+). Unit files are architecture independent (hence, not %{_lib}) and needed early in the boot process."

This makes RPM build fail with error:
File not found: /home/test/rpmbuild/BUILDROOT/tpm2-abrmd-1.1.0-2.el7.x86_64/usr/lib/systemd/system/tpm2-abrmd.service

**Comment by flihp** [comment]
Hi @yunyings. The installation instructions (in INSTALL.md) are a bit deficient currently I'm afraid. PR #118 should fix this. In the meantime you can use `--with-systemdunitdir` to control the install location for the systemd unit file.

**Comment by flihp** [comment]
Just merged #118. The section you're looking for is: https://github.com/01org/tpm2-abrmd/blob/master/INSTALL.md#systemd-uint---with-systedsystemunitdir

**Comment by yunyings** [comment]
Thanks Philip. Adding "--with-systemdsystemunitdir=%{_unitdir}" during configure works for Fedora.
BTW, there's a minor typo in INSTALL.md - missing a "m" in "--with-syste**m**dsystemunitdir=/lib/systemd/system".

**Comment by yunyings** [comment]
This issue can be closed.
