### ISSUE TITLE
can't compile - "access-broker.c:545:34: error: 'MAX_LOADED_OBJECTS1' undeclared"

### ISSUE THREAD

**Issue by iasiccsc** [01org/tpm2-abrmd#117]
make failed. It gave err:

access-broker.c: In function 'access_broker_get_trans_object_count':
src/access-broker.c:545:34: error: 'MAX_LOADED_OBJECTS1' undeclared (first use in this function)
                                  TRANSIENT_LAST - TRANSIENT_FIRST,
                                  ^
Please advice. Thanks!

**Comment by flihp** [comment]
this was fixed upstream in 92a0830306c2eb3081b5ac3329f7504cd58d670b in the master branch, 0acc8e37cd4f3738d21ccc1ec43ac7d9aebf6277 in the 1.x release branch. You need to update your TSS to the latest release: https://github.com/01org/TPM2.0-TSS/releases/tag/1.1.0

If this doesn't fix your issue feel free to re-open it with new details.
