### ISSUE TITLE
add a number prefix to the name of udev rules file?

### ISSUE THREAD

**Issue by yunyings** [01org/tpm2-abrmd#132]
"man udev" shows: 
"All rules files are collectively sorted and processed in **lexical** order, regardless of the directories in which they live."

Checking all udev rules files under /usr/lib/udev/rules.d/ or /etc/udev/rules.d/ in RHEL, they all start with a numeric number in file names:
```
$ ls -al /usr/lib/udev/rules.d/
total 792
drwxr-xr-x. 2 root root   8192 May 10 11:08 .
drwxr-xr-x. 4 root root   4096 Jan  1  1998 ..
-r--r--r--. 1 root root   7266 Sep 28  2016 10-dm.rules
-r--r--r--. 1 root root   2454 Sep 28  2016 11-dm-lvm.rules
-rw-r--r--. 1 root root   1577 Sep  8  2016 11-dm-mpath.rules
-r--r--r--. 1 root root   1499 Sep 28  2016 13-dm-disk.rules
-rw-r--r--. 1 root root 180730 Jan 26  2014 40-libgphoto2.rules
-rw-r--r--. 1 root root    843 Sep 13  2016 40-redhat.rules
-rw-r--r--. 1 root root  38082 Jul 25  2016 40-usb_modeswitch.rules
-rw-r--r--. 1 root root   2207 Sep 13  2016 42-usb-hid-pm.rules
-rw-r--r--. 1 root root    226 Jun 23  2016 50-rbd.rules
-rw-r--r--. 1 root root   3252 Sep 13  2016 50-udev-default.rules
-rw-r--r--. 1 root root    584 Jun 14  2016 56-hpmud.rules
-rw-r--r--. 1 root root    357 Sep 13  2016 60-alias-kmsg.rules
-rw-r--r--. 1 root root    910 Sep 13  2016 60-cdrom_id.rules
-rw-r--r--. 1 root root    153 Sep 13  2016 60-drm.rules
-rw-r--r--. 1 root root   6782 Apr 12  2016 60-fprint-autosuspend.rules
-rw-r--r--. 1 root root    821 Sep 13  2016 60-keyboard.rules
-rw-r--r--. 1 root root    129 Sep 12  2016 60-net.rules
...
```

Should we rename current "tpm-udev.rules" to "70-tpm-udev.rules" or something like that?

**Comment by flihp** [comment]
Is there any significance to the `70`?

**Comment by yunyings** [comment]
Seems the rules files are parsed in lexical order, so rules in file with a larger number prefix may overwrite same rules in a lexical small prefix rules file. 

"man udev" has:
`The udev rules are read from the files located in the system rules directory /usr/lib/udev/rules.d, the volatile runtime directory /run/udev/rules.d and the local administration directory /etc/udev/rules.d. All **rules files are collectively sorted and processed in lexical order**, regardless of the directories in which they live. However, files with identical file names replace each other. Files in /etc have the highest priority, files in /run take precedence over files with the same name in /lib. This can be used to override a system-supplied rules file with a local file if needed; a symlink in /etc with the same name as a rules file in /lib, pointing to /dev/null, disables the rules file entirely.`

About file prefix, http://hackaday.com/2009/09/18/how-to-write-udev-rules/ has something about it:
```
    Files should be named xx-descriptive-name.rules, the xx should be
    chosen first according to the following sequence points:

    < 60  most user rules; if you want to prevent an assignment being
    overriden by default rules, use the := operator.

    these cannot access persistent information such as that from
    vol_id

    < 70  rules that run helpers such as vol_id to populate the udev db

    < 90  rules that run other programs (often using information in the
    udev db)

    >=90  rules that should run last
```

Can't find more detailed info.. I will try rename rules file to "60-tpm-udev.rules", and put it under "/usr/lib/udev/rules.d/" for Fedora.

**Comment by flihp** [comment]
@yunyings : how about #157?

**Comment by yunyings** [comment]
That will solve this issue. Thanks Philip.

**Comment by flihp** [comment]
Np
