### ISSUE TITLE
preset file is needed to run daemon after package installation

### ISSUE THREAD

**Issue by yunyings** [01org/tpm2-abrmd#134]
When packing tpm2-abrmd for Fedora, it is found that tpm2-abrmd service is un-able to run automatically after package installation with scriptlet:
%post
%systemd_post tpm2-abrmd.service 

According to package guideline(https://fedoraproject.org/wiki/Packaging:Scriptlets?rd=Packaging:ScriptletSnippets#Systemd ):
`If your package includes one or more systemd units that need to be enabled by default on package installation, they MUST be covered by the Fedora preset policy.`

that is, to enable a service/daemon after installation, a preset file is needed to specifiy the enble/disable of this service. Preset file format:
https://www.freedesktop.org/software/systemd/man/systemd.preset.html

Is there any plan for upstream to add preset file for tpm2-abrmd?

**Comment by flihp** [comment]
I don't know much about systemd so this is the first I've read about these preset files. I don't see any reason we can't support one like we do the service file. Are you already providing a preset file for your packaging efforts? Could we just pick that up here (in a PR)?

**Comment by yunyings** [comment]
I've not create a preset file yet. Currently on RHEL 7.3, as far as I can see, tpm2-abrmd service does not get started after package installed and system restarts. Service does not get started after package installation either. But manually run "tpm2-abrmd" does work fine.

Philip, does tpm2-abrmd daemon gets started automatically at system boot up on Ubuntu? Have you tried tpm2-abrmd on RHEL 7.x or Fedora?

If you have time to try it on RHEL/Fedora, here is the tpm2-abrmd-1.1.0 RPM:
https://koji.fedoraproject.org/koji/taskinfo?taskID=21239219

**Comment by flihp** [comment]
Sorry I missed this last question. Anyways the daemon should start on system boot. If you can provide an example preset file I'll integrate it like the unit file.

**Comment by flihp** [comment]
The rpm you provided didn't have a preset file in it, or at least when I dumped the contents of the rpm I couldn't find one. So I took an educated guess as to what should be done in the build. Some feedback on #160 would be appreciated.

**Comment by flihp** [comment]
just merged a preset file in #160. There still seem to be some problems with this file or some other related systemd stuff on RHEL based on feedback from @yunyings. I'm closing this ticket since we now have the relevant file but it's looking like we'll end up with a new issue to figure out whatever's going on with the RHEL / Fedora packages.
