### ISSUE TITLE
Possible race condition in `command_source_thread()` regarding `source->receive_fdset`

### ISSUE THREAD

**Issue by mgerstner** [01org/tpm2-abrmd#155]
While working on PR #154 I noticed what I think might be a possible race condition between the `command_source_thread()` reading `source->receive_fdset` and the main thread adding new clients via `command_source_on_new_connection()` to the same set.

In rare cases this could lead to the `command_source_thread()` using a bad/old/wrong `receive_fdset`.

Utilizing a `pthread_mutex` for this might be advisable.

**Comment by flihp** [comment]
This is a good find @mgerstner . I ran across this a while back while hunting a bug with @dguerri but completely forgot to create an issue for it.

**Comment by flihp** [comment]
#185 should resolve this issue. I'm in the process of refactoring the IPC front end code to be more flexible and a big part of this is moving away from handling raw FDs and using GIO objects instead. #185 removes the use of FDs in favor of GSockets exclusively. This means I had to remove the use of `select` with the `fd_set` replacing it with GSource callbacks driven by a GMainLoop.

If you have time to review the PR to ensure it addresses your concerns here that would be much appreciated.

**Comment by flihp** [comment]
Should be resolved now so I'm closing the issue. Feel free to re-open or create a new one if you believe the issue persists.
