### ISSUE TITLE
Running tpm2-abrmd with "-t socket" fails (against tpm_server simulator)

### ISSUE THREAD

**Issue by rtkypoeluev** [01org/tpm2-abrmd#168]
Trying to use a socket option to connect to the tpm_server simulator (https://sourceforge.net/projects/ibmswtpm2/), with different versions 532 and 974.
The ABRM daemon exists without any error message, and on the tpm_server side everything as normal:
```
Client accepted
Client accepted
Platform server listening on port 2322
TPM command server listening on port 2321 
```
The resourcemgr daemon works fine with the tpm_server, but new TSS doesn't use resourcemgr anymore. I've also tried various releases of tpm2-abrmd with different releases of tpm2-tss, no luck.

Any solution on how to make these components work together and what versions should work together?

- tpm_server as TPM device simulator
- tpm2-abrmd as a resource manager/broker
- tpm2-tss
- tpm2-tools

By replacing tpm_server with a real TPM hardware works well by the way, it's just the simulator part breaks this model, very unfortunate. I'm running these components on Ubuntu 16.04.
It would be good for someone to try and confirm.

Thanks!

**Comment by flihp** [comment]
The newer emulators return `TPM_RC_RETRY` in some cases (not sure why). It's a valid response code so we should handle it properly. The thing that worries me the most is that the daemon is failing with no useful error message.

I just fixed up the TSS test harness to use the new simulator. Will get on the test harness here too.

**Comment by flihp** [comment]
I've just merged #170 to update the automated test harness. It now uses the 974 version of the tpm2 emulator. This didn't require any changes to the daemon, just the test cases (proper handling of the TPM_RC_RETRY response code).

Given this I'm inclined to think the issue may lie elsewhere. The tpm2-tools project has a compatibility matrix [https://github.com/01org/tpm2-tools/wiki](https://github.com/01org/tpm2-tools/wiki) which is where you should start (a good point you make above). After that I'd ask for more data:
1) what versions you're using
2) how you're starting the daemon (systemd vs. manually in a terminal)
3) run the daemon in a terminal with `G_MESSAGES_DEBUG=all` in it's environment

This last bit should get you lots of log output that will help us debug more / better.

**Comment by rtkypoeluev** [comment]
To help by answering your questions: 

1. I started using the master branch, which means the latest. That didn't work well, so I tried using previous releases that would matter the most I think (some of them might not be compatible but I wanted to try them anyway):
  - TSS, versions 0.97, 1.0, 1.1.0, 1.2.0
  - IBM TPM, versions 532 and 974

2. I start the daemon manually in a terminal
`sudo tpm2-abrmd -t socket`

3. Thanks for the tip on turning on debug messaging. Please see the debug messages attached.

Hope this helps to troubleshoot.

Thanks

[log.txt](https://github.com/01org/tpm2-abrmd/files/1277547/log.txt)

**Comment by rtkypoeluev** [comment]
I've tried the latest official dependencies on the Wiki, https://github.com/01org/tpm2-tools/wiki

tpm2-tools version | tpm2-tss version | tpm2-abrmd version
-- | -- | --
2.1.0 | 1.2.0 | 1.1.1

Getting the same results and the same log messages.

Thanks

**Comment by rtkypoeluev** [comment]
An update, I was finally able to use the latest dependencies from the table

tpm2-tools version | tpm2-tss version | tpm2-abrmd version
-- | -- | --
2.1.0 | 1.2.0 | 1.1.1

One additional step was required for ABMR, `sudo make install`. I was running it locally in the build directory, but there must be something in "install" that makes this difference in behavior. I will try the latest master branch at some point.

Thanks

**Comment by flihp** [comment]
Glad you're making progress @rtkypoeluev. Happy to have someone kicking the proverbial tires on the master branches as well. When you start working on this be sure to walk through the [INSTALL.md](./INSTALL.md).

We've had to work through similar issues in the past and some of them are documented in some closed issues. I think the most relevant here is #92 which covered installing udev and dbus config files. #92 prompted a rewrite of the [INSTALL.md](./INSTALL.md) file so if you find anything that's not documented there, or is inaccurate let me know and we can fix it up to help whoever comes along next.

Since you've resolved your issue using the latest releases I'm going to close this issue out. If you run into any additional issues with the master branch just open another ticket and we can work through it there.
