### ISSUE TITLE
tpm2_abrmd service restarts silently.

### ISSUE THREAD

**Issue by Magicloud** [01org/tpm2-abrmd#213]
Just built tss/abrmd/tools on Ubuntu Xenial. With some help from Issues here, I finally got `systemctl start tpm2-abrmd` run without error. But later I noticed tpm2-abrmd just existed silently and systemd was restarting it repeatedly. Turned out, I have put dbus-1/system.d/tpm2-abrmd.conf in wrong place. After move it to /etc/dbus-1/system.d/, everything works.
```
# journalctl -xe
-- Unit tpm2-abrmd.service has finished starting up.
-- 
-- The start-up result is done.
10月 12 15:05:52 myLaptop systemd[1]: tpm2-abrmd.service: Service hold-off time over, scheduling restart.
10月 12 15:05:52 myLaptop systemd[1]: Stopped TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has finished shutting down.
10月 12 15:05:52 myLaptop systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has begun starting up.
10月 12 15:05:52 myLaptop systemd[1]: Started TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has finished starting up.
-- 
-- The start-up result is done.
10月 12 15:05:57 myLaptop systemd[1]: tpm2-abrmd.service: Service hold-off time over, scheduling restart.
10月 12 15:05:57 myLaptop systemd[1]: Stopped TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has finished shutting down.
10月 12 15:05:57 myLaptop systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has begun starting up.
10月 12 15:05:57 myLaptop systemd[1]: Started TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has finished starting up.
-- 
-- The start-up result is done.
```

**Comment by flihp** [comment]
There are two likely issues and both should show up in syslog (if not -> bug). Check to make sure the dbus and udev config are installed to the right location for Ubuntu. I think the dbus config should be in `/etc/dbus-1/system.d` and the udev rules at `/lib/udev/rules.d`. Debugging this is probably easier if you're starting the daemon on the command line directly as the `tss` user: `sudo -u tss ${prefix}/sbin/tpm2-abrmd`. If you need to get debug output from the daemon you can set the `G_MESSAGES_DEBUG` environment variable to `all`.

**Comment by Magicloud** [comment]
This is why this issue being cut. I found no valuable information in syslog when dbus conf was in wrong place and the process just exited.

**Comment by flihp** [comment]
Can you provide some info about what version of the `tabrmd` you're using? The commit that attempted to make this situation more visible and clear to the user only went in to the code ~2 weeks ago (https://github.com/01org/tpm2-abrmd/commit/4a76ed1e330eae84391dabdcdb20142085376edf) so it may not be in the version you're using.

Can you try again with the HEAD of the 1.x branch to see if you at least get an error message in syslog identifying the problem?

**Comment by flihp** [comment]
assuming issue was resolved since no additional data provided. Please re-open with requested data if not resolved.
