### ISSUE TITLE
ibm974 simulator causes Tss2_Sys_Startup returned unexpected RC: 0x144

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2-abrmd#224]
Running the newest ibm software tpm simulator, abrmd chokes on a Tss2_Sys_Startup rc of: 0x144

Simulator: https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm974.tar.gz

Reproduction steps:
1. Start the tpm_server for ibmtpm974
2. Start abrmd with the socket tcti

```
$ sudo -u tss tpm2-abrmd --tcti=socket

** (tpm2-abrmd:31179): WARNING **: Tss2_Sys_Startup returned unexpected RC: 0x144

** (tpm2-abrmd:31179): ERROR **: access_broker_sent_tpm_startup failed: 0x144
Trace/breakpoint trap (core dumped)
```

**Comment by flihp** [comment]
Ugh, sorry bout that. I'm cleaning up an implementation of EncryptDecrypt2 for the tss now. I'll pick this up next.

**Comment by flihp** [comment]
I wasn't able to repro this when I tried yesterday. I'm going to clean out a few things on my dev system to be sure I'm not using an older version w/o realizing it. Any additional details you can provide (full debug log by defining `G_MESSAGES_DEBUG=all`) would be helpful.
