### ISSUE TITLE
syslog handler ignores G_MESSAGES_DEBUG

### ISSUE THREAD

**Issue by flihp** [01org/tpm2-abrmd#30]
When the tpm2-abrmd is started with `--logger=syslog` the log level is dialed up all the way regardless of the state of G_MESSAGES_DEBUG. This is a bug in the `syslog_log_handler` function.

**Comment by dguerri** [comment]
hey! I am being hit hard by this :)

**Comment by flihp** [comment]
Sorry @dguerri. Are you using systemd? A quick work around that I'm using is to have tabrmd log to stdout but have systemd redirect stdout / stderr to syslog for me. Any chance this hack will hold you over till we can get a "real" fix in place?

**Comment by lamalexck** [comment]
Yea, I got hit by this earlier too.

Apparently,

G_MESSAGES_DEBUG.  A space-separated list of log domains for which informational and debug messages should be printed. By default, these messages are not printed. You can also use the special value all. This environment variable only affects the default log handler, g_log_default_handler().

So, when we use --logger=syslog  content in G_MESSAGES_DEBUG is ignored.

My workaround is identical to Phil’s
ie, remove “—logger=syslog” and let systemd logs tambrd’s stdout/stderr into syslog for you.

**Comment by dguerri** [comment]
@flihp np! Unfortunately I don't use systemd, but I use a quick patch for the moment.

**Comment by dguerri** [comment]
@lamalexck yep. A possible fix would be to set the handler only for the desired levels, or check the desired levels inside the handler function, I guess.
For the moment I am quickly patching out DEBUG, INFO and MESSAGES.

**Comment by flihp** [comment]
It's not "the right way" to do it, but #97 is probably good enough to unblock you and keep you from having to carry around a patch to remove logging calls.
