### ISSUE TITLE
resource_manager_flush_context returns TSS2_RC_SUCCESS instead of Tpm2Response pointer

### ISSUE THREAD

**Issue by PeterHuewe** [01org/tpm2-abrmd#56]
The function resource_manager_flush_context has the following prototype:

```
Tpm2Response*
resource_manager_flush_context (ResourceManager *resmgr,
                                Tpm2Command     *command)
```

but returns   `TSS2_RC_SUCCESS` in some cases.
Is it desired to return a `NULL` pointer in these cases?
or would it be better to return a status word. (and not a pointer)

clang of course complains
```
src/resource-manager.c:460:16: error: expression which evaluates to zero treated as a null pointer constant of type 'Tpm2Response *'
      (aka 'struct _Tpm2Response *') [-Werror,-Wnon-literal-null-conversion]
        return TSS2_RC_SUCCESS;
               ^~~~~~~~~~~~~~~
/usr/local/include/sapi/tss2_common.h:149:49: note: expanded from macro 'TSS2_RC_SUCCESS'
#define TSS2_RC_SUCCESS                         ((TSS2_RC)0)
                                                ^~~~~~~~~~~~
```

I don't know what is the desired way to fix this.

**Comment by flihp** [comment]
Me either. Will queue this one up for tomorrow. Thanks for digging into the clang stuff. Already paying off.

**Comment by flihp** [comment]
Was a bit slow getting around to this one ...

Took a look just now and this check can just go away. The function is only called internally and the same check is already made by the caller (https://github.com/01org/tpm2-abrmd/blob/master/src/resource-manager.c#L819). I guess it would be equally valid to create a response object for the RC in this case like we do here: https://github.com/01org/tpm2-abrmd/blob/master/src/resource-manager.c#L485.

I'll see how these look in practice.

**Comment by flihp** [comment]
I've looked at this from a few different angles and IMHO the right thing to do is just return NULL here. PR is https://github.com/01org/tpm2-abrmd/pull/64. Will be merging shortly.
