### ISSUE TITLE
Please allow multiple contexts to be created by one process on client

### ISSUE THREAD

**Issue by dguerri** [01org/tpm2-abrmd#83]
Hi Philip, as per our chat:

Given #82 (which is how the code was intended to work), it is not possible to create multiple context per client process, as dbus will always use the same id. 

Please allow creating more that one context per process as it was allowed on the old RM.

**Comment by flihp** [comment]
Yup yup. After our exchange this morning I managed to repro. This was my misunderstanding of how https://developer.gnome.org/gio/stable/GDBusMethodInvocation.html#g-dbus-method-invocation-get-sender works. We'll have to go back to adding an integer component to the connection ID to make the ID unique.

Should have something out pretty quick.

**Comment by dguerri** [comment]
Thanks! ;)
