### ISSUE TITLE
tpm2-abrmd run command for non-simulator tpm

### ISSUE THREAD

**Issue by idesai** [01org/tpm2-abrmd#92]
sudo -u tss tpm2-abrmd
** (tpm2-abrmd:1838): WARNING **: failed to initialize device TCTI context: 0xa000a

** (tpm2-abrmd:1838): CRITICAL **: TCTI initialization failed: 0xa000a

tpm2_rc_decode 0xa000a
error layer
  hex: 0xa0000
  identifier: TSS2_TCTI_ERROR_LEVEL
  description: Error from the TCTI
base error code
  identifier: TSS2_BASE_RC_IO_ERROR
  description: IO failure

**Comment by idesai** [comment]
Solved this by running without -u tss option
So run this just with 
sudo tpm2-abrmd

**Comment by flihp** [comment]
What were the permissions on the TPM device node?:
```
$ls -l /dev/tpm*
???
```

**Comment by lamalexck** [comment]
Perhaps the udev.conf  was not correctly installed
One may need to use the --with-udevrulesdir  configure options to install it at the right place to set /dev/tpm*  owner correctly.

**Comment by flihp** [comment]
spot on @lamalexck : https://github.com/01org/tpm2-abrmd/blob/master/INSTALL.md#d-bus

**Comment by flihp** [comment]
whoops, meant to link https://github.com/01org/tpm2-abrmd/blob/master/INSTALL.md#udev

**Comment by idesai** [comment]
Thanks!

**Comment by flihp** [comment]
thx for working through this and posting the results. It's a bit obnoxious that the default `prefix`is never the default directory for a distro's dbus / udev rules dir. Still if you know your distro the configurability makes customization easy. In the ideal end state distros will take care of all of this crap for the majority of users. Only devs like yourself need to know these details :)
