### ISSUE TITLE
Please consider making optional tss2_tcti_tabrmd_init_full (or put it in a separate .h)

### ISSUE THREAD

**Issue by dguerri** [01org/tpm2-abrmd#93]
`tss2_tcti_tabrmd_init_full` needs `<gio/gio.h>`. 

Every client application which includes `tcti-tabrmd.h` will depend on Glib2 (i.e. will have to search for `glib.h` and `glibconfig.h`).
Since `tss2_tcti_tabrmd_init_full` was introduced just for debugging purposes, it would be cool to "hide" the actual transport mechanism to clients (the dynamic library will still depend on Glib, of course).

_If_ that sounds reasonable, `tss2_tcti_tabrmd_init_full` could be put in a separate include file or just could be made optional (selectable via configure).

**Comment by flihp** [comment]
I think the most simple approach is to remove the glib stuff from the header. This can be done by replacing the use of GBusType with our own enum. Does this get you the desired behavior @dguerri? See #94 for proposed solution.

**Comment by dguerri** [comment]
It's brilliant. Thanks!
