### ISSUE TITLE
getting MAX_COMMANDS exceeded

### ISSUE THREAD

**Issue by dguerri** [01org/tpm2-abrmd#98]
From time to time I am getting the following error:
`ERROR **: Failed to create connection with service: GDBus.Error:com.intel.tss2.Tabrmd.Error.General: MAX_COMMANDS exceeded. Try again later.`

I appreciate that the maximum number of connections should be 27 by default and I am pretty sure I am not flooding the RM (of course using -c XX could mitigate the issue).
I will provide more details and some debug output asap.

**Comment by flihp** [comment]
You can always use `--max-connections` to increase this but if it's a legit bug in the connection tracking logic this may just delay the inevitable. While we were working through #83 it looked like your stuff was making multiple connections from a single process. Any chance this is your applicationis leaking connections to the daemon?

**Comment by dguerri** [comment]
The super weird thing is that using -c 64, made it worse. 
I am investigating the #83 issue, but I am using a different application in this case (which doesn't seem to "leak" an extra connection).
Of course as soon I restart the RM with debugging output, I can't reproduce it....

**Comment by flihp** [comment]
Ain't that the way it always is ... :sweat_smile:

**Comment by dguerri** [comment]
That actually makes me think that the problem is elsewhere as when I restart the RM, other apps using it are restarted as well. I think you could be right :)

**Comment by dguerri** [comment]
yes we are leaking in an "unexpected" place 👍 
Closing as it's invalid! 
Thanks

**Comment by flihp** [comment]
Any time @dguerri.
